services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWK_SET_URI=${JWK_SET_URI}