spring:
  application:
    name: taco-cloud-auth-server
  datasource:
    # By default, the database name is randomly generated.
    # But that we want to have jdbc url like this for h2 connection:
    # jdbc:h2:mem:tacocloud
    url: jdbc:h2:mem:tacocloudauthserver
    username: sa  # Default username for H2
    password:     # Default password for H2 (leave empty for no password)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # this one is for visibility of the console from docker...

server:
  port: 9000  #oauth2 authorization server